title:  lsaffie
description: My notes and principles
tagline: Luis is technologist with passion for building motivated teams and high impact products
theme: jekyll-theme-slate
plugins:
  - jekyll-twitter-plugin
